import React from 'react';
import { Users, PhoneCall, MessageCircle, BadgeCheck, TrendingUp } from 'lucide-react';
import MetricCard from './MetricCard';

const DashboardTab = ({ stats }) => {
  return (
    <div className="tab-content">
      <div className="tab-header">
        <h2>Live Metrics Overview</h2>
        <p>Real-time performance tracking for Maya AI</p>
      </div>

      <div className="summary-cards">
        <MetricCard 
          title="Total Leads Created" 
          value={stats.total_leads || 0} 
          icon={Users} 
          trend="+12%" 
          color="purple" 
        />
        <MetricCard 
          title="Total Voice Calls" 
          value={stats.total_calls || 0} 
          icon={PhoneCall} 
          trend="+5%" 
          color="blue" 
        />
        <MetricCard 
          title="Chat Interactions" 
          value={stats.total_chats || 0} 
          icon={MessageCircle} 
          trend="+18%" 
          color="cyan" 
        />
      </div>

      <div className="metrics-grid">
        <div className="metric-card-wide glass">
          <div className="card-inner">
            <div className="metric-info">
              <h3>Lead Attribution</h3>
              <p>Generated by Maya Voice AI</p>
              <div className="progress-container">
                <div className="progress-bar" style={{ width: '85%' }}></div>
              </div>
              <p className="percent">85% of total leads</p>
            </div>
            <div className="metric-value">
              <span className="big-number">{stats.leads_by_maya || 0}</span>
              <span className="label">Maya Leads</span>
            </div>
          </div>
        </div>

        <div className="metric-card-wide glass accent">
          <div className="card-inner">
            <div className="metric-info">
              <h3>Conversion Success</h3>
              <p>Qualified Leads to Sales</p>
              <div className="progress-container">
                <div className="progress-bar success" style={{ width: '24%' }}></div>
              </div>
              <p className="percent">24% target rate</p>
            </div>
            <div className="metric-value">
              <span className="big-number">{stats.conversions || 0}</span>
              <span className="label">Converted</span>
            </div>
          </div>
        </div>
      </div>
      
      <div className="dashboard-footer-info">
          <TrendingUp size={16} />
          <span>Real-time data synchronization enabled. Last updated: {new Date(stats.last_updated).toLocaleString()}</span>
      </div>
    </div>
  );
};

export default DashboardTab;
